### PR TITLE
tray icons; .pid-based singleInstance mechanism for dllCaller.ahk

### PR DESCRIPTION
**Pull request by bits-of-static**
nothing special...but the standard icon ain't especially good. Especially not for ahk-developers trying out new snippets :)

### CODE REVIEW

**Comment by bits-of-static** [comment]
I just noticed the dllCaller.ahk also has the default icon. Could be removed from tray by adding #NoTrayIcon to the autoexecute section.

**Comment by bits-of-static** [comment]
`Process, waitclose` consumes quite some resources - you can consider my #persistent #SingleInstance, force solution.

**Comment by jpginc** [comment]
sorry for the slow reply, i like the idea of a custom icon. not sure what your doing with the ensureSingleInstancePropertyOrDie function?

**Comment by bits-of-static** [comment]
Monitoring when a window closes requires a constant loop in the background and eats about 2% CPU. As far as I understood, it's just a dll-hook which is made available for the system, so it's ok if it stays loaded and idle even when app should close.

Replaced by .pid mechanism -- slightly different semantics, but it also allows reload. Kills the old instance and creates a new one.

Reloading mainly a feature for developer, but everyone profits from the saved cycles.

**Comment by jpginc** [comment]
just got a chance to see the new icon, looks good. thanks for your effort

**Pull request merged**
